<?php

/**
 * Inform about attempyt to insert dupliacted value to database.
 * Should be thrown when database insert might be duplicated.
 * @author anza
 */
class DuplicateException extends SQLException
{
	/**
	 * Extract value from array generated by mysqli_error.
	 * @return void
	 */
	public function getField()
	{
		$extracted = explode('key ', $this->message);
		return str_replace('\'', '', $extracted[1]);
	}
}

?>